"""film-quality-diagnostics — technical checks on real local media.

Every clip here is a small synthetic fixture generated by ffmpeg in the
test (testsrc / color / sine sources only — no real artwork, no network,
no paid call). Diagnostics measure the file; the report carries
`not_an_approval` and the classification records are user judgements over
measured evidence — never an aesthetic score or a Final approval. Tests
skip when ffmpeg is unavailable, matching the suite's media conventions.
"""
import shutil
import subprocess
import sys
from fractions import Fraction
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent))
from test_compiler_v03 import fixture_project  # noqa: E402

from engine.compiler import compile_preview  # noqa: E402
from engine.core import FilmError, digest, read, write  # noqa: E402
from engine.quality_diagnostics import (  # noqa: E402
    classify_finding, diagnose_build, diagnose_media, expect_contract,
    intended_regions, load_report, normalize_intended, parse_intended)

FFMPEG = shutil.which("ffmpeg")
pytestmark = pytest.mark.skipif(FFMPEG is None,
                                reason="ffmpeg is not installed")


def _ffmpeg(*args):
    subprocess.run([FFMPEG, "-hide_banner", "-loglevel", "error", "-y",
                    *[str(a) for a in args]], check=True)


def _clip(target, *, seconds=2, extra_vf=None, audio="sine"):
    """A 320x240/24 testsrc + mono-sine delivery-shaped MP4."""
    video = f"testsrc=size=320x240:rate=24:duration={seconds}"
    cmd = ["-f", "lavfi", "-i", video,
           "-f", "lavfi", "-i",
           f"sine=frequency=440:sample_rate=44100:duration={seconds}"
           + ("," + audio if audio not in ("sine", None) else "")]
    cmd += ["-map", "0:v:0"]
    if audio is not None:
        cmd += ["-map", "1:a:0"]
    if extra_vf:
        cmd += ["-vf", extra_vf]
    cmd += ["-c:v", "libx264", "-pix_fmt", "yuv420p"]
    if audio is not None:
        cmd += ["-c:a", "aac"]
    _ffmpeg(*cmd, target)


def _truncated(source, target, fraction=55):
    """Truncate a +faststart MP4 — the header parses but the decode dies
    mid-file, the honest shape of a damaged delivery."""
    fast = source.with_name(source.stem + "_fs.mp4")
    _ffmpeg("-i", source, "-c", "copy", "-movflags", "+faststart", fast)
    data = fast.read_bytes()
    target.write_bytes(data[:len(data) * fraction // 100])


@pytest.fixture
def clips(tmp_path):
    out = tmp_path / "clips"
    out.mkdir()
    _clip(out / "normal.mp4")
    _truncated(out / "normal.mp4", out / "truncated.mp4")
    # One dropped frame slot mid-stream — a real PTS discontinuity the
    # muxer keeps (passthrough timestamps, packet 10 shows at 11/24).
    _ffmpeg("-i", out / "normal.mp4", "-vf", "select='not(eq(n,10))'",
            "-fps_mode", "passthrough", "-an", "-c:v", "libx264",
            "-pix_fmt", "yuv420p", out / "pts_gap.mp4")
    # 0.5 s blackout head, then motion.
    _ffmpeg("-f", "lavfi", "-i",
            "color=c=black:size=320x240:rate=24:duration=0.5",
            "-f", "lavfi", "-i",
            "testsrc=size=320x240:rate=24:duration=1.5",
            "-f", "lavfi", "-i",
            "sine=frequency=440:sample_rate=44100:duration=2",
            "-filter_complex", "[0:v][1:v]concat=n=2:v=1[v]",
            "-map", "[v]", "-map", "2:a:0",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
            out / "black.mp4")
    # 18 cloned tail frames — an undeclared still.
    _ffmpeg("-f", "lavfi", "-i",
            "testsrc=size=320x240:rate=24:duration=2",
            "-f", "lavfi", "-i",
            "sine=frequency=440:sample_rate=44100:duration=2.75",
            "-filter_complex", "[0:v]tpad=stop=18:stop_mode=clone[v]",
            "-map", "[v]", "-map", "1:a:0",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
            out / "still.mp4")
    _clip(out / "silent.mp4",
          audio="volume='if(between(t,0.5,1.5),0,1)':eval=frame")
    _clip(out / "clipped.mp4", audio="volume=40")
    return out


def _findings(report, kind=None, severity=None):
    return [f for f in report["findings"]
            if (kind is None or f["kind"] == kind)
            and (severity is None or f["severity"] == severity)]


def _base_expect(**kw):
    return expect_contract(fps=24, seconds=2, audio_streams=1,
                           audio_channels=1, **kw)


# --- the frame-clock contract -------------------------------------------------


def test_240_seconds_at_24fps_is_5760_frames():
    expect = expect_contract(fps=24, seconds=240)
    assert expect["frames"] == 5760
    assert expect_contract(fps=24, frames=5760)["frames"] == 5760
    # A duration that does not land on a frame boundary is not a contract.
    with pytest.raises(FilmError):
        expect_contract(fps=24, seconds=Fraction(1001, 1000))


def test_normal_clip_passes_clean(clips):
    report = diagnose_media(clips / "normal.mp4", expect=_base_expect())
    assert report["not_an_approval"] is True
    assert not _findings(report, severity="DEFECT")
    assert not _findings(report, severity="CANDIDATE")
    video = report["artifacts"]["normal.mp4"]["measurements"]["video"]
    assert video["decoded_frames"] == 48
    assert video["packet_count"] == 48
    assert video["pts_anomalies"] == 0
    audio = report["artifacts"]["normal.mp4"]["measurements"]["audio"]
    assert audio["channels"] == 1
    assert audio["decoded_samples"] > 0


# --- decode / PTS / duration ---------------------------------------------------


def test_truncated_clip_reports_decode_defects(clips):
    report = diagnose_media(clips / "truncated.mp4", expect=_base_expect())
    defects = _findings(report, severity="DEFECT")
    kinds = {f["kind"] for f in defects}
    assert kinds & {"DECODE_ERROR", "TRUNCATED_DECODE", "PROBE_ERROR"}
    assert "FRAME_COUNT_MISMATCH" in kinds
    for finding in defects:
        assert finding["repro"].startswith(("ffmpeg", "ffprobe", "python"))
        assert finding["location"]["stream"] in \
            {"video", "audio", "container"}


def test_pts_discontinuity_is_a_defect_with_a_location(clips):
    report = diagnose_media(
        clips / "pts_gap.mp4",
        expect=expect_contract(fps=24, frames=48))
    gap = _findings(report, "PTS_DISCONTINUITY", "DEFECT")
    assert len(gap) == 1
    assert gap[0]["location"]["start_frame"] == 10
    assert "11/24" in gap[0]["detail"]
    assert _findings(report, "FRAME_COUNT_MISMATCH", "DEFECT")


def test_frame_count_mismatch_is_reported(clips):
    report = diagnose_media(
        clips / "normal.mp4",
        expect=expect_contract(fps=24, frames=50))
    mismatches = _findings(report, "FRAME_COUNT_MISMATCH", "DEFECT")
    assert mismatches
    assert "48" in mismatches[0]["detail"]


def test_duration_mismatch_is_reported(clips):
    report = diagnose_media(
        clips / "normal.mp4",
        expect=expect_contract(fps=24, seconds=3))
    assert _findings(report, "DURATION_MISMATCH", "DEFECT")


# --- audio checks --------------------------------------------------------------


def test_audio_channel_count_mismatch(clips):
    report = diagnose_media(
        clips / "normal.mp4",
        expect=expect_contract(fps=24, seconds=2, audio_streams=1,
                               audio_channels=2))
    mismatch = _findings(report, "AUDIO_CHANNELS_MISMATCH", "DEFECT")
    assert mismatch and "1 channel" in mismatch[0]["detail"]


def test_missing_audio_stream_is_a_defect(clips, tmp_path):
    _clip(tmp_path / "silent_track.mp4", audio=None)
    report = diagnose_media(
        tmp_path / "silent_track.mp4",
        expect=expect_contract(fps=24, seconds=2, audio_streams=1))
    assert _findings(report, "STREAM_COUNT", "DEFECT")


def test_silence_run_candidate_becomes_intended_when_declared(clips):
    report = diagnose_media(clips / "silent.mp4", expect=_base_expect())
    run = _findings(report, "SILENCE_RUN")
    assert run and run[0]["severity"] == "CANDIDATE"
    assert 500 <= run[0]["location"]["start_ms"] <= 700
    declared = [{"kind": "SILENCE", "start_ms": 400, "end_ms": 1600}]
    report = diagnose_media(clips / "silent.mp4", expect=_base_expect(),
                            intended=declared)
    run = _findings(report, "SILENCE_RUN")
    assert run and all(f["severity"] == "INTENDED" for f in run)
    # A declaration covering only part of the run does not excuse it.
    partial = [{"kind": "SILENCE", "start_ms": 500, "end_ms": 1000}]
    report = diagnose_media(clips / "silent.mp4", expect=_base_expect(),
                            intended=partial)
    assert _findings(report, "SILENCE_RUN", "CANDIDATE")


def test_clipping_run_is_a_candidate(clips):
    report = diagnose_media(clips / "clipped.mp4", expect=_base_expect())
    runs = _findings(report, "CLIPPING_RUN", "CANDIDATE")
    assert runs
    assert all(f["location"]["stream"] == "audio" for f in runs)
    assert all(f["repro"].startswith("ffmpeg") for f in runs)


# --- black frames / stills ------------------------------------------------------


def test_black_run_candidate_and_intended(clips):
    report = diagnose_media(clips / "black.mp4", expect=_base_expect())
    run = _findings(report, "BLACK_RUN")
    assert len(run) == 1 and run[0]["severity"] == "CANDIDATE"
    assert run[0]["location"]["start_frame"] == 0
    report = diagnose_media(
        clips / "black.mp4", expect=_base_expect(),
        intended=[{"kind": "BLACK", "start_ms": 0, "end_ms": 600}])
    run = _findings(report, "BLACK_RUN")
    assert len(run) == 1 and run[0]["severity"] == "INTENDED"


def test_still_run_candidate_and_intended(clips):
    report = diagnose_media(
        clips / "still.mp4",
        expect=expect_contract(fps=24, seconds=Fraction(11, 4)))
    run = _findings(report, "STILL_RUN")
    assert run and all(f["severity"] == "CANDIDATE" for f in run)
    report = diagnose_media(
        clips / "still.mp4",
        expect=expect_contract(fps=24, seconds=Fraction(11, 4)),
        intended=[{"kind": "STILL", "start_ms": 2200, "end_ms": 2800}])
    run = _findings(report, "STILL_RUN")
    assert run and all(f["severity"] == "INTENDED" for f in run)


def test_parse_and_normalize_intended():
    parsed = parse_intended("BLACK:0-500, still:1000-2000 ")
    assert parsed == [{"kind": "BLACK", "start_ms": 0, "end_ms": 500,
                       "source": "declared"},
                      {"kind": "STILL", "start_ms": 1000, "end_ms": 2000,
                       "source": "declared"}]
    with pytest.raises(FilmError):
        parse_intended("BLUR:0-500")
    with pytest.raises(FilmError):
        normalize_intended([{"kind": "BLACK", "start_ms": 500,
                             "end_ms": 0}])


# --- declared intent on the animation contract -----------------------------------


def _pins(count=1):
    return [{"asset_id": f"A{i + 1:04d}", "revision": 1,
             "content_sha256": "0" * 64} for i in range(count)]


def _layer(slots, drawings=1, transform=None, track="layer"):
    return {"drawings": _pins(drawings), "transform": transform,
            "mask": None,
            "exposure": [{"track": track, "start": 0,
                          "end": slots[-1]["end"], "stride": 1,
                          "phase": 0, "slots": slots}]}


def _shot_plan(shot_id, intent, camera=None, layers=None):
    return {"document_type": "animation_shot_plan", "schema_version": 1,
            "shot_id": shot_id, "motion_intent": intent,
            "tracks": {"camera": {"pivot": [0, 0], "transform": camera},
                       "layers": layers or {}}}


def _store_plan(p, plan):
    from engine.animation_schema import write_canon
    write_canon(Path(p) / "animation" / "shots" / plan["shot_id"]
                / "plan.json", plan)


def test_static_motion_intent_declares_the_whole_cut(tmp_path):
    from test_anim_003 import animation_project
    p = animation_project(tmp_path)
    # motion_intent STATIC is the human's declaration — a moving camera
    # or a several-drawing table does not withdraw it.
    camera = {"channels": {"translate": {
        "curve": "LINEAR",
        "keys": [{"frame": 0, "value": [0, 0]},
                 {"frame": 12, "value": [40, 0]}]}}}
    layer = _layer([{"start": i, "end": i + 1, "drawing": i % 2}
                    for i in range(24)], drawings=2)
    _store_plan(p, _shot_plan("S001", "STATIC", camera=camera,
                              layers={"subject": layer}))
    stills = [d for d in intended_regions(p) if d["kind"] == "STILL"]
    assert stills == [{"kind": "STILL", "start_ms": 0, "end_ms": 1000,
                       "source": "S001 motion_intent STATIC"}]


def test_animated_plan_static_identity_declares_nothing(tmp_path):
    from test_anim_003 import animation_project
    p = animation_project(tmp_path)
    # Null transforms and one drawing are just static identity on an
    # ANIMATED plan — an undeclared freeze must stay a CANDIDATE.
    layer = _layer([{"start": i, "end": i + 1, "drawing": 0}
                    for i in range(24)])
    _store_plan(p, _shot_plan("S001", "ANIMATED",
                              layers={"subject": layer}))
    assert not [d for d in intended_regions(p) if d["kind"] == "STILL"]


def test_declared_exposure_hold_marks_only_the_held_frames(tmp_path):
    from test_anim_003 import animation_project
    p = animation_project(tmp_path)
    slots = ([{"start": i, "end": i + 1, "drawing": 0}
              for i in range(8)]
             + [{"start": 8, "end": 16, "drawing": 0, "hold": True}]
             + [{"start": i, "end": i + 1, "drawing": 0}
                for i in range(16, 24)])
    layers = {"a": _layer(slots, track="a"), "b": _layer(slots, track="b")}
    _store_plan(p, _shot_plan("S001", "ANIMATED", layers=layers))
    stills = [d for d in intended_regions(p) if d["kind"] == "STILL"]
    assert stills == [{"kind": "STILL", "start_ms": 333, "end_ms": 666,
                       "source": "S001 declared exposure hold"}]
    # A hold on only one layer is not a whole-frame still.
    layers["b"] = _layer([{"start": i, "end": i + 1, "drawing": 0}
                          for i in range(24)], track="b")
    _store_plan(p, _shot_plan("S001", "ANIMATED", layers=layers))
    assert not [d for d in intended_regions(p) if d["kind"] == "STILL"]


def test_render_mode_still_scope_is_legacy_only(tmp_path):
    from test_anim_003 import animation_project
    p = animation_project(tmp_path)
    # render_mode is a LEGACY_MV field; on the animation profile the
    # plan's motion_intent/hold declarations are the contract.
    shots = read(Path(p) / "manifest/shots.json")
    for shot in shots:
        shot["render_mode"] = "STATIC"
    write(Path(p) / "manifest/shots.json", shots)
    assert not [d for d in intended_regions(p) if d["kind"] == "STILL"]


# --- sealed-build diagnosis ------------------------------------------------------


@pytest.fixture
def built(tmp_path):
    """A real sealed Build 1 preview of a synthetic project."""
    p = fixture_project(tmp_path, seconds=2, shot_count=2)
    result = compile_preview(p)
    return p, result["build_id"]


def test_diagnose_build_links_findings_to_provenance(built):
    p, build_id = built
    report = diagnose_build(p, build_id)
    assert report["not_an_approval"] is True
    assert report["subject"]["build_id"] == build_id
    assert report["subject"]["build_json_sha256"] \
        == digest(Path(p) / "builds" / build_id / "build.json")
    record = read(Path(p) / "builds" / build_id / "build.json")
    assert set(report["artifacts"]) \
        == {"MASTER_SUBBED.mp4", "MASTER_CLEAN.mp4"}
    for name, artifact in report["artifacts"].items():
        prov = artifact["provenance"]
        assert prov["build_id"] == build_id
        assert prov["artifact_sha256"] == digest(
            Path(p) / "builds" / build_id / name)
        assert prov["artifact_sha256_recorded"] == record["files"][name]
    assert report["findings"], "a storyboard-hold fixture must measure stills"
    for finding in report["findings"]:
        assert finding["provenance"]["build_id"] == build_id
        assert finding["repro"]
        assert finding["location"]["stream"]


def test_diagnose_build_stores_the_report_and_leaves_bytes_alone(built):
    p, build_id = built
    build_dir = Path(p) / "builds" / build_id
    before = {f: digest(f) for f in build_dir.rglob("*") if f.is_file()}
    lock_path = Path(p) / "manifest/locks.json"
    lock_before = lock_path.read_bytes() if lock_path.is_file() else None
    report = diagnose_build(p, build_id)
    stored = load_report(p, build_id)
    assert stored is not None
    assert stored["findings"] == report["findings"]
    assert {f: digest(f) for f in build_dir.rglob("*") if f.is_file()} \
        == before
    assert (lock_path.read_bytes() if lock_path.is_file() else None) \
        == lock_before


def test_static_shot_declares_an_intended_still(tmp_path):
    p = fixture_project(tmp_path, seconds=2, shot_count=2)
    shots = read(Path(p) / "manifest/shots.json")
    shots[0]["render_mode"] = "STATIC"
    write(Path(p) / "manifest/shots.json", shots)
    declared = intended_regions(p)
    still = [d for d in declared if d["kind"] == "STILL"]
    assert still and still[0]["start_ms"] == 0
    assert still[0]["end_ms"] == 1000
    result = compile_preview(p)
    report = diagnose_build(p, result["build_id"])
    intended = _findings(report, "STILL_RUN", "INTENDED")
    candidate = _findings(report, "STILL_RUN", "CANDIDATE")
    # Shot 1's declared still is INTENDED; shot 2's undeclared hold stays
    # a candidate for a human to classify.
    assert any(f["location"]["end_ms"] <= 1000 for f in intended)
    assert any(f["location"]["start_ms"] >= 1000 for f in candidate)


def test_artifact_tampering_is_a_defect(built):
    p, build_id = built
    target = Path(p) / "builds" / build_id / "MASTER_CLEAN.mp4"
    target.write_bytes(target.read_bytes() + b"tamper")
    report = diagnose_build(p, build_id)
    assert _findings(report, "ARTIFACT_HASH_MISMATCH", "DEFECT")


def test_failed_or_missing_build_is_an_error(built):
    p, _ = built
    with pytest.raises(FilmError):
        diagnose_build(p, "B9999")


def test_report_paths_reject_non_build_ids(built):
    p, build_id = built
    report = diagnose_build(p, build_id)
    finding = report["findings"][0]
    for bad in ("../reviews/r1", "../../etc/hostname", "x", "B1"):
        with pytest.raises(FilmError):
            diagnose_build(p, bad)
        with pytest.raises(FilmError):
            load_report(p, bad)
        with pytest.raises(FilmError):
            classify_finding(p, bad, finding["id"], "DEFECT", "reason",
                             "reviewer")
    # A lookalike JSON elsewhere under qc/ is never read or rewritten.
    planted = Path(p) / "qc/reviews/r1.json"
    write(planted, {"findings": [{"id": "F001", "key": "k",
                                  "severity": "CANDIDATE"}]})
    with pytest.raises(FilmError):
        classify_finding(p, "../reviews/r1", "F001", "DEFECT", "reason",
                         "reviewer")
    assert read(planted)["findings"] == [{"id": "F001", "key": "k",
                                          "severity": "CANDIDATE"}]


def test_build_audio_contract_path_stays_inside_the_build(built):
    p, build_id = built
    record_path = Path(p) / "builds" / build_id / "build.json"
    record = read(record_path)
    record["audio"]["path"] = "../../analysis/audio.json"
    write(record_path, record)
    with pytest.raises(FilmError):
        diagnose_build(p, build_id)


def test_font_finding_repro_names_the_build(built):
    p, build_id = built
    # Point the subtitle font at a non-font file: the cmap check cannot
    # verify coverage, so a FONT_* finding is guaranteed on any box.
    config = read(Path(p) / "project.yaml")
    config["subtitles"] = {"font_file": "input/brief.md"}
    write(Path(p) / "project.yaml", config)
    report = diagnose_build(p, build_id)
    fonts = [f for f in report["findings"] if f["kind"].startswith("FONT_")]
    assert fonts
    assert all(f["repro"].endswith("--build " + build_id) for f in fonts)


def test_master_silence_regions_cover_detection_window_edges(tmp_path,
                                                           clips):
    (tmp_path / "proj").mkdir()
    p = fixture_project(tmp_path / "proj", seconds=2, shot_count=1)
    measured = diagnose_media(clips / "silent.mp4", expect=_base_expect())
    run = _findings(measured, "SILENCE_RUN", "CANDIDATE")[0]
    a, b = run["location"]["start_ms"], run["location"]["end_ms"]
    # The analyzer's hop-grid region can sit just inside the measured
    # run; one detection window of tolerance keeps it INTENDED.
    analysis = read(Path(p) / "analysis/audio.json")
    analysis["silence_regions"] = [{"in_ms": a + 40, "out_ms": b - 40}]
    write(Path(p) / "analysis/audio.json", analysis)
    declared = intended_regions(p)
    silence = [d for d in declared if d["kind"] == "SILENCE"]
    assert silence == [{"kind": "SILENCE", "start_ms": a + 40 - 50,
                        "end_ms": b - 40 + 50,
                        "source": "measured master silence_regions"}]
    report = diagnose_media(clips / "silent.mp4", expect=_base_expect(),
                            intended=declared)
    assert all(f["severity"] == "INTENDED"
               for f in _findings(report, "SILENCE_RUN"))


# --- classification ---------------------------------------------------------------


def test_classify_candidate_with_reason(built):
    p, build_id = built
    report = diagnose_build(p, build_id)
    finding = _findings(report, severity="CANDIDATE")[0]
    artifact = Path(p) / "builds" / build_id / finding["artifact"]
    before = digest(artifact)
    updated = classify_finding(p, build_id, finding["id"], "DEFECT",
                               "the still is an encode stall, not an "
                               "editorial hold", "fixture reviewer")
    stored = next(f for f in updated["findings"]
                  if f["id"] == finding["id"])
    assert stored["classification"]["decision"] == "DEFECT"
    assert stored["classification"]["reason"]
    assert stored["classification"]["reviewer"] == "fixture reviewer"
    assert stored["classification"]["classified_at"]
    assert digest(artifact) == before
    updated = classify_finding(p, build_id, finding["id"],
                               "ACCEPTED_INTENDED",
                               "director confirmed the hold",
                               "fixture reviewer")
    assert next(f for f in updated["findings"]
                if f["id"] == finding["id"])["classification"]["decision"] \
        == "ACCEPTED_INTENDED"


def test_classify_validation(built):
    p, build_id = built
    report = diagnose_build(p, build_id)
    finding = report["findings"][0]
    with pytest.raises(FilmError):
        classify_finding(p, build_id, finding["id"], "APPROVED",
                         "not a real decision", "reviewer")
    with pytest.raises(FilmError):
        classify_finding(p, build_id, finding["id"], "DEFECT",
                         "   ", "reviewer")
    with pytest.raises(FilmError):
        classify_finding(p, build_id, finding["id"], "DEFECT",
                         "reason", "  ")
    with pytest.raises(FilmError):
        classify_finding(p, build_id, "F999", "DEFECT", "reason",
                         "reviewer")
    with pytest.raises(FilmError):
        classify_finding(p, "B9999", finding["id"], "DEFECT", "reason",
                         "reviewer")


def test_defect_cannot_be_excused_as_intended(built):
    p, build_id = built
    target = Path(p) / "builds" / build_id / "MASTER_CLEAN.mp4"
    target.write_bytes(target.read_bytes() + b"tamper")
    report = diagnose_build(p, build_id)
    defect = _findings(report, "ARTIFACT_HASH_MISMATCH", "DEFECT")[0]
    with pytest.raises(FilmError):
        classify_finding(p, build_id, defect["id"], "ACCEPTED_INTENDED",
                         "trying to excuse a spec violation", "reviewer")
    updated = classify_finding(p, build_id, defect["id"], "DEFECT",
                               "confirmed: the artifact changed after "
                               "sealing", "reviewer")
    assert next(f for f in updated["findings"]
                if f["id"] == defect["id"])["classification"]["decision"] \
        == "DEFECT"


def test_classification_survives_a_rediagnosis(built):
    p, build_id = built
    report = diagnose_build(p, build_id)
    finding = _findings(report, severity="CANDIDATE")[0]
    classify_finding(p, build_id, finding["id"], "ACCEPTED_INTENDED",
                     "the director confirmed the hold", "fixture reviewer")
    again = diagnose_build(p, build_id)
    stored = next(f for f in again["findings"]
                  if f["key"] == finding["key"])
    assert stored["classification"]["decision"] == "ACCEPTED_INTENDED"
    assert stored["classification"]["reason"]


def test_report_is_not_an_approval_and_not_a_score(built):
    p, build_id = built
    report = diagnose_build(p, build_id)
    assert report["not_an_approval"] is True
    # No finding or summary carries a score or an approval — diagnostics
    # only ever report measured evidence.
    assert "score" not in report
    assert all("score" not in f and "approval" not in f
               for f in report["findings"])
    # A diagnostics report never writes a review or LOCK record.
    p_path = Path(p)
    reviews = list(p_path.rglob("reviews/*.json")) \
        + list(p_path.rglob("qc/reviews/*"))
    assert not reviews
    assert not read(p_path / "manifest/locks.json", {})
